import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import GlobalContext from "@/context/global-context";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "@/context/theme";
import { Suspense } from "react";
import LayoutContainer from "@/components/core/layout/LayoutContainer";


export const metadata: Metadata = {
  title: "Item Database",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
          <GlobalContext>
            <Suspense>
              <LayoutContainer>
                {children}
              </LayoutContainer>
            </Suspense>
          </GlobalContext>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
