import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import GlobalContext from "@/context/global-context";


export const metadata: Metadata = {
  title: "Item Database",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col p-6">
        <AppRouterCacheProvider>
          <GlobalContext>
            {children}
          </GlobalContext>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
